=begin
#MELI Markeplace SDK

#This is a the codebase to generate a SDK for Open Platform Marketplace

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Meli::CategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CategoriesApi' do
  before do
    # run before each test
    @api_instance = Meli::CategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoriesApi' do
    it 'should create an instance of CategoriesApi' do
      expect(@api_instance).to be_instance_of(Meli::CategoriesApi)
    end
  end

  # unit tests for categories_category_id_get
  # Return by category.
  # @param category_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'categories_category_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sites_site_id_categories_get
  # Return a categories by site.
  # @param site_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sites_site_id_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sites_site_id_domain_discovery_search_get
  # Predictor
  # @param site_id 
  # @param q 
  # @param limit 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sites_site_id_domain_discovery_search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
