=begin
#MELI Markeplace SDK

#This is a the codebase to generate a SDK for Open Platform Marketplace

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Meli::ItemsHealthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ItemsHealthApi' do
  before do
    # run before each test
    @api_instance = Meli::ItemsHealthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ItemsHealthApi' do
    it 'should create an instance of ItemsHealthApi' do
      expect(@api_instance).to be_instance_of(Meli::ItemsHealthApi)
    end
  end

  # unit tests for items_id_health_actions_get
  # Return item health actions by id.
  # @param id 
  # @param access_token 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'items_id_health_actions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for items_id_health_get
  # Return health by id.
  # @param id 
  # @param access_token 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'items_id_health_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sites_site_id_health_levels_get
  # Return health levels.
  # @param site_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sites_site_id_health_levels_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
