=begin
#MELI Markeplace SDK

#This is a the codebase to generate a SDK for Open Platform Marketplace

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Meli::RestClientApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RestClientApi' do
  before do
    # run before each test
    @api_instance = Meli::RestClientApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RestClientApi' do
    it 'should create an instance of RestClientApi' do
      expect(@api_instance).to be_instance_of(Meli::RestClientApi)
    end
  end

  # unit tests for resource_delete
  # Resource path DELETE
  # @param resource 
  # @param access_token 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'resource_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for resource_get
  # Resource path GET
  # @param resource 
  # @param access_token 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'resource_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for resource_post
  # Resourse path POST
  # @param resource 
  # @param access_token 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'resource_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for resource_put
  # Resourse path PUT
  # @param resource 
  # @param access_token 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'resource_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
