=begin
#MELI Markeplace SDK

#This is a the codebase to generate a SDK for Open Platform Marketplace

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Meli::ItemPictures
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ItemPictures' do
  before do
    # run before each test
    @instance = Meli::ItemPictures.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ItemPictures' do
    it 'should create an instance of ItemPictures' do
      expect(@instance).to be_instance_of(Meli::ItemPictures)
    end
  end
  describe 'test attribute "source"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
