=begin
#MELI Markeplace SDK

#This is a the codebase to generate a SDK for Open Platform Marketplace

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'Meli/api_client'
require 'Meli/api_error'
require 'Meli/version'
require 'Meli/configuration'

# Models
require 'Meli/models/attributes'
require 'Meli/models/attributes_value_struct'
require 'Meli/models/attributes_values'
require 'Meli/models/inline_object'
require 'Meli/models/item'
require 'Meli/models/item_pictures'
require 'Meli/models/variations'
require 'Meli/models/variations_attribute_combinations'

# APIs
require 'Meli/api/categories_api'
require 'Meli/api/items_api'
require 'Meli/api/items_health_api'
require 'Meli/api/o_auth20_api'
require 'Meli/api/rest_client_api'

module Meli
  class << self
    # Customize default settings for the SDK using block.
    #   Meli.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
